### ISSUE TITLE
Slot Machine reels flickers when using an image

### ISSUE THREAD

**Issue by jlorencelim** [atlanteh/react-native-slot-machine#6]
The reels in the slot machine flickers whenever I use an image for the reels instead of a plain text. The flicker happens every time after the slot machine finishes spinning. Is there a way to fix this problem?

**Comment by atlanteh** [comment]
Honestly, this module doesn't work well with images, as the images don't render fast enough on RN (especially on android). You can try using it with react-native-fast-image and it might speed up the images rendering.
As for the flickering, I think this is a little bit of a problem due to the current implementation.
If you want to have a look and fix that, that'd be great.

**Comment by sabbyt54** [comment]
I had the same issue on emulator but surprisingly did not flicker on a build. Note I used local images.
